"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
exports.router = router;
const UniversityRenderController_1 = require("./UniversityRenderController");
const univrersityRenderController = new UniversityRenderController_1.UnivrersityRenderController();
const ProgramRenderController_1 = require("./ProgramRenderController");
const programRenderController = new ProgramRenderController_1.ProgramRenderController();
const SubscriptionController_1 = require("./SubscriptionController");
const subscriptionController = new SubscriptionController_1.SubscriptionController();
const UniversityController_1 = require("./UniversityController");
const universityController = new UniversityController_1.UniversityController();
const ProgramController_1 = require("./ProgramController");
const programController = new ProgramController_1.ProgramController();
const ProgramMajorController_1 = require("./ProgramMajorController");
const programMajorController = new ProgramMajorController_1.ProgramMajorController();
const ProgramCommentController_1 = require("../../comment/controllers/ProgramCommentController");
const programCommentController = new ProgramCommentController_1.ProgramCommentController();
router.get('/vuz/:universityAlias/specialnost/:programAlias', programRenderController.actionGetInformation);
router.get('/program/search', programRenderController.actionGetSearch);
router.get('/', univrersityRenderController.actionGetHome);
router.get('/program/filtersearch', programController.actionSearch);
router.get('/program/geosearch', programController.actionGeoSuggestSearch);
router.get('/program/filtersearch/count', programController.actionGetSearchCount);
router.get('/university/suggest', universityController.actionSuggestSearch);
router.post('/program/subscribe', subscriptionController.actionCreate);
router.post('/program/:programId/comment', programCommentController.actionChange);
router.get('/programmajor/search', programMajorController.actionSearch);
router.get('/programmajor/popular', programMajorController.actionGetPopular);
